### ISSUE TITLE
docker build error

### ISSUE THREAD

**Issue by sarancopper** [mikekelly/AgentK#1]
I tried to build this repo in my windows machine. I got this error.

Reading package lists...
Building dependency tree...
Reading state information...
E: Unable to locate package wget
E: Unable to locate package curl
E: Unable to locate package git
E: Unable to locate package chromium-driver

Error log: 
![image](https://github.com/user-attachments/assets/e96fcacf-a99f-4741-95f9-8de63262dd13)

**Comment by sarancopper** [comment]
I changed Dockerfile and got successful build

```
FROM python:3.9-slim-bullseye

RUN apt-get update && apt-get install -y \
    wget \
    curl \
    git \
    chromium-driver \
    ca-certificates \
    && rm -rf /var/lib/apt/lists/*

WORKDIR /app
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

COPY . .
ENTRYPOINT ["python", "agent_kernel.py"]

```

**Comment by moffefei** [comment]
> I changed Dockerfile and got successful build
> 
> ```
> FROM python:3.9-slim-bullseye
> 
> RUN apt-get update && apt-get install -y \
>     wget \
>     curl \
>     git \
>     chromium-driver \
>     ca-certificates \
>     && rm -rf /var/lib/apt/lists/*
> 
> WORKDIR /app
> COPY requirements.txt .
> RUN pip install --no-cache-dir -r requirements.txt
> 
> COPY . .
> ENTRYPOINT ["python", "agent_kernel.py"]
> ```

it works

**Comment by mikekelly** [comment]
Have you opened/modified `apt-packages-list.txt` on your host windows machine?

Each package name might be appended with a carriage return (\r) when the file is processed in a Windows environment, causing apt-get to fail to locate the packages.

We're trying to avoid hardcoding dependencies in the Dockerfile, a better fix for this might be to add `RUN sed -i 's/\r$//' apt-packages-list.txt` on the line above `RUN xargs -a apt-packages-list.txt apt-get install -y` - please could you try this and confirm it resolves the issue on windows

**Comment by cubic461** [comment]
i cannot make it work on windows. please help by making a install and run guide. thank you

**Comment by AW-Creates** [comment]
> i cannot make it work on windows. please help by making a install and run guide. thank you
I ran into an issue as well on windows. Follow this guide: https://www.youtube.com/watch?v=POGsJd2TQhk

Just be sure to edit the "Dockerfile" as well and replace it with this code while you're editing the "env.example" file:

FROM python:3.9-slim-bullseye

RUN apt-get update && apt-get install -y \
    wget \
    curl \
    git \
    chromium-driver \
    ca-certificates \
    && rm -rf /var/lib/apt/lists/*

WORKDIR /app
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

COPY . .
ENTRYPOINT ["python", "agent_kernel.py"]

**Comment by sarancopper** [comment]
Yes @mikekelly it works.
