### ISSUE TITLE
transformers error on mac

### ISSUE THREAD

**Issue by NGOcoins** [mikekelly/AgentK#9]
Hi,

Any help would be appreciated.
./agentk
WARN: Could not load agent "content_creator". ModuleNotFoundError: No module named 'transformers'
WARN: Could not load tool "select_best_frames". ModuleNotFoundError: No module named 'cv2'
WARN: Could not load tool "split_video_into_frames". ModuleNotFoundError: No module named 'cv2'
WARN: Could not load tool "generate_text". ModuleNotFoundError: No module named 'transformers'
WARN: Could not load agent "content_creator". ModuleNotFoundError: No module named 'transformers'
WARN: Could not load tool "select_best_frames". ModuleNotFoundError: No module named 'cv2'
WARN: Could not load tool "split_video_into_frames". ModuleNotFoundError: No module named 'cv2'
WARN: Could not load tool "generate_text". ModuleNotFoundError: No module named 'transformers'
WARN: Could not load tool "select_best_frames". ModuleNotFoundError: No module named 'cv2'
WARN: Could not load tool "split_video_into_frames". ModuleNotFoundError: No module named 'cv2'
WARN: Could not load tool "generate_text". ModuleNotFoundError: No module named 'transformers'

**Comment by mikekelly** [comment]
Those are tools and agents that AgentK has created but contain errors and therefore can't be loaded.

**Comment by mikekelly** [comment]
I'm working on making the system more robust when it comes to detecting and fixing errors in modules it's creating.
